### ISSUE TITLE
Seems unnecessary

### ISSUE THREAD

**Issue by Deletrius366** [Garuda-1/JA-HW02#1]
https://github.com/Garuda-1/JA-HW02/blob/f5da3e0e3842bf2c842099491e374a50287c7302/src/ru/ifmo/rain/dolzhanskii/arrayset/ArraySet.java#L14

**Comment by Garuda-1** [comment]
1) In some cases, an empty set is returned while information about comparator might be still important.
2) Tests fail due to the aforesaid cause.

**Comment by Deletrius366** [comment]
Can you give me an example? I can't imagine such situation - if we have empty unmod set, we don't need comparator

**Comment by Garuda-1** [comment]
See ```subSet()```.

**Comment by Deletrius366** [comment]
I see, but I wonder why can't we use just default comparator?

**Comment by Garuda-1** [comment]
I wonder how you pass tests without this.

**Comment by Deletrius366** [comment]
Maybe, you will answer my question instead of requestion?) My code is working fine, don't worry

**Comment by Garuda-1** [comment]
Looks like sometimes it is needed to retrieve comparator from possibly empty set:
```
java.lang.AssertionError: invalid comparator in subSet(2050720011, false, -474581297, false) (comparator = All equal, elements = [579308562, -834001867, -909181242] expected same:<All equal> was not:<null>
```

**Comment by Deletrius366** [comment]
You can use (list, comp) constructor. OK, if you want this constructor - you may leave it, but you can do everything without it. Drop if you want

**Comment by Garuda-1** [comment]
Glad we understood each other. I think I'll leave it this way.
