### ISSUE TITLE
Better to use just descendingSet().iterator()

### ISSUE THREAD

**Issue by Deletrius366** [Garuda-1/JA-HW02#10]
https://github.com/Garuda-1/JA-HW02/blob/f5da3e0e3842bf2c842099491e374a50287c7302/src/ru/ifmo/rain/dolzhanskii/arrayset/ArraySet.java#L164

**Comment by Garuda-1** [comment]
Fixed.

**Comment by Deletrius366** [comment]
Please, close issue if u've fixed
