### ISSUE TITLE
Why not default constructor? It will be used if you delete unnecessary constructor from comparator

### ISSUE THREAD

**Issue by Deletrius366** [Garuda-1/JA-HW02#13]
https://github.com/Garuda-1/JA-HW02/blob/f5da3e0e3842bf2c842099491e374a50287c7302/src/ru/ifmo/rain/dolzhanskii/arrayset/ArraySet.java#L197

**Comment by Garuda-1** [comment]
This causes tests failure for me.

**Comment by Deletrius366** [comment]
It is not a motivation)

**Comment by Garuda-1** [comment]
See #1

**Comment by Garuda-1** [comment]
Fixed.
