### ISSUE TITLE
Should be checked that fromElement <= toElement and exception should be thrown otherwise

### ISSUE THREAD

**Issue by Deletrius366** [Garuda-1/JA-HW02#14]
https://github.com/Garuda-1/JA-HW02/blob/f5da3e0e3842bf2c842099491e374a50287c7302/src/ru/ifmo/rain/dolzhanskii/arrayset/ArraySet.java#L192

**Comment by Garuda-1** [comment]
Tests fail if an exception is thrown.
IMHO, checking indexes is enough. Less dirt rather than comparing via comparator or comparable interface.

**Comment by Deletrius366** [comment]
You are not right. According to docs of subSet(), you MUST throw an exception in case of fromElement > toElement

**Comment by Garuda-1** [comment]
That really makes sense, I agree. But here's what I can find among failed tests:
```
Test test14_subSet failed: null
java.lang.IllegalArgumentException
	at ru.ifmo.rain.dolzhanskii.arrayset.ArraySet.subSet(ArraySet.java:174)
	at ru.ifmo.rain.dolzhanskii.arrayset.ArraySet.subSet(ArraySet.java:199)
	at info.kgeorgiy.java.advanced.arrayset/info.kgeorgiy.java.advanced.arrayset.SortedSetTest.test14_subSet(Unknown Source)
```
Looks like only ```subSet()``` was invoked here.

**Comment by Deletrius366** [comment]
Update code and I can help you find the bug

**Comment by Garuda-1** [comment]
Fixed.
