### ISSUE TITLE
ClassCastException?

### ISSUE THREAD

**Issue by Deletrius366** [Garuda-1/JA-HW02#2]
https://github.com/Garuda-1/JA-HW02/blob/f5da3e0e3842bf2c842099491e374a50287c7302/src/ru/ifmo/rain/dolzhanskii/arrayset/ArraySet.java#L34

**Comment by Garuda-1** [comment]
According to the documentation, the method is expected to throw ```ClassCastException```.
https://docs.oracle.com/javase/7/docs/api/java/util/Set.html#contains(java.lang.Object)

**Comment by Deletrius366** [comment]
OK
