### ISSUE TITLE
ClassCastException and seems like you should factor it out. Here and further

### ISSUE THREAD

**Issue by Deletrius366** [Garuda-1/JA-HW02#4]
https://github.com/Garuda-1/JA-HW02/blob/f5da3e0e3842bf2c842099491e374a50287c7302/src/ru/ifmo/rain/dolzhanskii/arrayset/ArraySet.java#L48

**Comment by Garuda-1** [comment]
According to NavigableSet documentation, ClassCastException is thrown if given element cannot be compared to elements in collection:
https://docs.oracle.com/javase/7/docs/api/java/util/NavigableSet.html#lower(E)

What do you think should be refactored?

**Comment by Deletrius366** [comment]
I have mistaken with ClassCast, sorry. I mean, Collections.binarySearch(array, e, comparator) can be factored in function int name(T e), just style fix. If u want, u may drop

**Comment by Garuda-1** [comment]
If I get you right, I don't see any sense in wrapping a single-line function.

**Comment by Deletrius366** [comment]
As I said, as you wish but line will be shorter and only one argument

**Comment by Garuda-1** [comment]
OK, I think I'll drop it.
