### ISSUE TITLE
Maybe just -2?

### ISSUE THREAD

**Issue by Deletrius366** [Garuda-1/JA-HW02#5]
https://github.com/Garuda-1/JA-HW02/blob/f5da3e0e3842bf2c842099491e374a50287c7302/src/ru/ifmo/rain/dolzhanskii/arrayset/ArraySet.java#L50

**Comment by Garuda-1** [comment]
This is a more comprehensive record (-1 to invert return value ```-(insertionPoint) - 1``` and -1 to look at previous element).
