### ISSUE TITLE
Seems like index >=0, so -index-2 definetely <= -2

### ISSUE THREAD

**Issue by Deletrius366** [Garuda-1/JA-HW02#6]
https://github.com/Garuda-1/JA-HW02/blob/f5da3e0e3842bf2c842099491e374a50287c7302/src/ru/ifmo/rain/dolzhanskii/arrayset/ArraySet.java#L51

**Comment by Garuda-1** [comment]
So what is improvement proposition?

**Comment by Deletrius366** [comment]
At least, index == -1 is useless and you can remove it. Maybe, you can make function like checkedGet(), which will work like get(), but will return null if index illegal

**Comment by Garuda-1** [comment]
No longer actual.
