### ISSUE TITLE
if you use iterator I mentioned, you won't need to override methods, which modify your set 

### ISSUE THREAD

**Issue by Deletrius366** [Garuda-1/JA-HW02#8]
https://github.com/Garuda-1/JA-HW02/blob/f5da3e0e3842bf2c842099491e374a50287c7302/src/ru/ifmo/rain/dolzhanskii/arrayset/ArraySet.java#L90

**Comment by Garuda-1** [comment]
That is false. According to ```AbstractCollection``` source code, if not overriden method throws ```UnsupportedOperationException```.

Line 261:
http://hg.openjdk.java.net/jdk8u/jdk8u-dev/jdk/file/c5d02f908fb2/src/share/classes/java/util/AbstractCollection.java

**Comment by Deletrius366** [comment]
And it should throw, or I don't understand you. I meant, that iterator from unmod list will restrict mod operations automatically, so you don't need to override them

**Comment by Garuda-1** [comment]
I agree that removing the overridden method should take place, but there is a different cause.
